import { useState } from "react";
import { Avatar, Pill, Alert } from "../components/index.jsx";
import { Button } from "../components/Button.jsx";
import { Input } from "../components/Input.jsx";
import { fmt } from "../lib/utils.js";
import { useAppStore } from "../store/appStore.js";
import { UNITS, PROJECTS } from "../data/demo.js";

const sel = (err) => ({
  height:40, width:"100%", borderRadius:8, border:`1px solid ${err?"#E02424":"#D1D5DB"}`,
  padding:"0 12px", fontSize:14, color:"#111827", fontFamily:"inherit", outline:"none", background:"#fff",
});

const STATUS_STYLES = {
  active:     { color:"green", label:"Active"     },
  expiring:   { color:"amber", label:"Expiring"   },
  terminated: { color:"red",   label:"Terminated" },
};

const daysUntil = d => Math.ceil((new Date(d) - new Date()) / 86400000);

function Modal({ title, sub, onClose, children, footer }) {
  return (
    <div style={{ position:"fixed", inset:0, background:"rgba(0,0,0,0.45)", display:"flex", alignItems:"center", justifyContent:"center", zIndex:50, padding:16 }}>
      <div style={{ background:"#fff", borderRadius:16, width:"100%", maxWidth:500, maxHeight:"90vh", overflowY:"auto", boxShadow:"0 24px 64px rgba(0,0,0,0.18)" }}>
        <div style={{ padding:"20px 24px 16px", borderBottom:"1px solid #E5E7EB", display:"flex", alignItems:"center", justifyContent:"space-between" }}>
          <div>
            <div style={{ fontSize:16, fontWeight:600, color:"#111827" }}>{title}</div>
            {sub && <div style={{ fontSize:12, color:"#9CA3AF", marginTop:2 }}>{sub}</div>}
          </div>
          <button onClick={onClose} style={{ background:"none", border:"none", cursor:"pointer", color:"#9CA3AF", fontSize:20 }}>
            <i className="ti ti-x" aria-hidden />
          </button>
        </div>
        <div style={{ padding:"20px 24px", display:"flex", flexDirection:"column", gap:14 }}>{children}</div>
        {footer && <div style={{ padding:"16px 24px", borderTop:"1px solid #E5E7EB", display:"flex", gap:8, justifyContent:"flex-end" }}>{footer}</div>}
      </div>
    </div>
  );
}

// ─── Download lease as text file ──────────────────────────────────────────────
function downloadLease(lease, client, unit, project) {
  const text = `
LEASE AGREEMENT
===============================================
Nyxion Properties Pvt. Ltd.

PARTIES
-------
Landlord : Nyxion Properties Pvt. Ltd.
Tenant   : ${client?.name || "–"}
Email    : ${client?.email || "–"}
Phone    : ${client?.phone || "–"}
CNIC     : ${client?.cnic || "–"}

PROPERTY
--------
Project  : ${project?.name || "–"}
Address  : ${project?.address || "–"}
Unit     : Unit ${unit?.unitNo || "–"} · Floor ${unit?.floor || "–"}
Type     : ${unit?.type || "–"}
Size     : ${unit?.size || "–"}

TERMS
-----
Monthly rent     : ${fmt(lease.rentAmount)}
Security deposit : ${fmt(lease.securityDeposit)}
Lease start      : ${lease.startDate}
Lease end        : ${lease.endDate}
Notice period    : ${lease.noticePeriod} days
Status           : ${lease.status}

CLAUSES
-------
1. Rent is due on the 1st of every month.
2. Late payment incurs a penalty of 2% per month.
3. Sub-letting is not permitted without written consent from the landlord.
4. The tenant is responsible for minor repairs up to Rs. 5,000.
5. Either party must give ${lease.noticePeriod} days written notice to terminate.
6. This agreement is governed by the laws of Pakistan.

SIGNATURES
----------
Landlord: _______________________   Date: ___________
Tenant  : _______________________   Date: ___________

Generated by Propflow · Nyxion Labs
===============================================
`.trim();

  const blob = new Blob([text], { type:"text/plain" });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href     = url;
  a.download = `Lease_${client?.name?.replace(/\s+/g,"_")}_Unit${unit?.unitNo}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Create Lease Modal ───────────────────────────────────────────────────────
function CreateLeaseModal({ prefillClientId, prefillUnitId, onClose }) {
  const { clients, addLease, assignClientToUnit } = useAppStore();
  const [form, setForm] = useState({
    clientId:        prefillClientId || "",
    unitId:          prefillUnitId   || "",
    rentAmount:      prefillUnitId ? String(UNITS.find(u=>u.id===prefillUnitId)?.rent||"") : "",
    startDate:       "",
    endDate:         "",
    securityDeposit: "",
    noticePeriod:    "60",
  });
  const [errors, setErrors] = useState({});
  const [loading, setLoading] = useState(false);
  const set = k => e => setForm(f => ({ ...f, [k]: e.target.value }));

  const validate = () => {
    const e = {};
    if (!form.clientId)        e.clientId        = "Select a client";
    if (!form.unitId)          e.unitId          = "Select a unit";
    if (!form.rentAmount)      e.rentAmount      = "Enter monthly rent";
    if (!form.startDate)       e.startDate       = "Select start date";
    if (!form.endDate)         e.endDate         = "Select end date";
    if (!form.securityDeposit) e.securityDeposit = "Enter security deposit";
    return e;
  };

  const submit = async () => {
    const e = validate(); setErrors(e);
    if (Object.keys(e).length) return;
    setLoading(true);
    await new Promise(r => setTimeout(r, 700));
    setLoading(false);
    const lease = {
      id: "L_NEW_"+Date.now(),
      clientId: form.clientId, unitId: form.unitId,
      rentAmount: Number(form.rentAmount),
      securityDeposit: Number(form.securityDeposit),
      noticePeriod: Number(form.noticePeriod),
      startDate: form.startDate, endDate: form.endDate,
      status: "active",
    };
    addLease(lease);
    assignClientToUnit(form.unitId, form.clientId, Number(form.rentAmount));
    onClose();
  };

  const vacantUnits = UNITS.filter(u => u.status === "vacant");
  const selectedUnit = UNITS.find(u => u.id === form.unitId);
  const selectedProject = selectedUnit ? PROJECTS.find(p => p.id === selectedUnit.projectId) : null;

  return (
    <Modal title="Create lease" sub="New lease agreement" onClose={onClose}
      footer={<><Button variant="secondary" onClick={onClose}>Cancel</Button><Button loading={loading} onClick={submit} icon="ti-file-plus">Create lease</Button></>}>
      <div style={{ display:"flex", flexDirection:"column", gap:4 }}>
        <label style={{ fontSize:13, fontWeight:500, color:"#374151" }}>Client</label>
        <select value={form.clientId} onChange={set("clientId")} style={sel(errors.clientId)}>
          <option value="">Select client…</option>
          {clients.map(c => <option key={c.id} value={c.id}>{c.name} — {c.city||"–"}</option>)}
        </select>
        {errors.clientId && <span style={{ fontSize:12, color:"#E02424" }}>{errors.clientId}</span>}
      </div>
      <div style={{ display:"flex", flexDirection:"column", gap:4 }}>
        <label style={{ fontSize:13, fontWeight:500, color:"#374151" }}>Unit (vacant only)</label>
        <select value={form.unitId} onChange={e => {
          const u = UNITS.find(u => u.id === e.target.value);
          setForm(f => ({ ...f, unitId:e.target.value, rentAmount:u?String(u.rent):"" }));
        }} style={sel(errors.unitId)}>
          <option value="">Select unit…</option>
          {vacantUnits.map(u => {
            const p = PROJECTS.find(pr => pr.id === u.projectId);
            return <option key={u.id} value={u.id}>{p?.name} — Unit {u.unitNo} (Floor {u.floor}) · {fmt(u.rent)}/mo</option>;
          })}
        </select>
        {errors.unitId && <span style={{ fontSize:12, color:"#E02424" }}>{errors.unitId}</span>}
        {selectedUnit && (
          <div style={{ background:"#F9FAFB", border:"1px solid #E5E7EB", borderRadius:8, padding:"8px 12px", fontSize:12, color:"#6B7280" }}>
            {selectedProject?.name} — Unit {selectedUnit.unitNo} · Floor {selectedUnit.floor} · {selectedUnit.type}
            {selectedUnit.bedrooms ? ` · ${selectedUnit.bedrooms} bed` : ""}
            {selectedUnit.size ? ` · ${selectedUnit.size}` : ""}
          </div>
        )}
      </div>
      <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:12 }}>
        <Input label="Monthly rent (Rs.)" value={form.rentAmount} onChange={set("rentAmount")} placeholder="120000" error={errors.rentAmount} icon="ti-coin-rupee" />
        <Input label="Security deposit (Rs.)" value={form.securityDeposit} onChange={set("securityDeposit")} placeholder="360000" error={errors.securityDeposit} icon="ti-shield" />
      </div>
      <div style={{ display:"grid", gridTemplateColumns:"1fr 1fr", gap:12 }}>
        <Input label="Start date" type="date" value={form.startDate} onChange={set("startDate")} error={errors.startDate} />
        <Input label="End date" type="date" value={form.endDate} onChange={set("endDate")} error={errors.endDate} />
      </div>
      <div style={{ display:"flex", flexDirection:"column", gap:4 }}>
        <label style={{ fontSize:13, fontWeight:500, color:"#374151" }}>Notice period</label>
        <select value={form.noticePeriod} onChange={set("noticePeriod")} style={sel(false)}>
          <option value="30">30 days</option>
          <option value="60">60 days</option>
          <option value="90">90 days</option>
        </select>
      </div>
    </Modal>
  );
}

// ─── Leases Page ──────────────────────────────────────────────────────────────
export function LeasesPage() {
  const { leases, clients, updateLease } = useAppStore();
  const [filter, setFilter]     = useState("all");
  const [showCreate, setShowCreate] = useState(false);

  const filtered   = leases.filter(l => filter === "all" || l.status === filter);
  const active     = leases.filter(l => l.status === "active").length;
  const expiring   = leases.filter(l => l.status === "expiring").length;
  const terminated = leases.filter(l => l.status === "terminated").length;

  const terminate = (id) => {
    if (window.confirm("Terminate this lease? This will mark the unit as vacant.")) {
      updateLease(id, { status:"terminated" });
    }
  };

  return (
    <div className="p-5">
      {expiring > 0 && (
        <div className="mb-4">
          <Alert type="warning">{expiring} lease{expiring>1?"s are":" is"} expiring soon. Initiate renewal before the notice period deadline.</Alert>
        </div>
      )}

      <div className="grid grid-cols-3 gap-3 mb-5">
        {[
          [active,     "Active leases",  "#1C64F2","#EBF5FF","ti-file-text"        ],
          [expiring,   "Expiring soon",  "#B45309","#FFFBEB","ti-clock-exclamation"],
          [terminated, "Terminated",     "#6B7280","#F3F4F6","ti-file-off"         ],
        ].map(([v,l,fg,bg,ic]) => (
          <div key={l} className="bg-white border border-gray-200 rounded-xl p-4 shadow-sm">
            <div className="flex items-center gap-2 mb-2">
              <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background:bg }}>
                <i className={`ti ${ic} text-[14px]`} style={{ color:fg }} aria-hidden />
              </div>
              <span className="text-[12px] text-gray-400">{l}</span>
            </div>
            <div className="text-2xl font-bold text-gray-900 font-mono">{v}</div>
          </div>
        ))}
      </div>

      <div className="flex items-center justify-between mb-4">
        <div className="flex gap-1.5">
          {[["all","All"],["active","Active"],["expiring","Expiring"],["terminated","Terminated"]].map(([v,l]) => (
            <button key={v} onClick={() => setFilter(v)}
              className={`px-3.5 py-1.5 rounded-lg border text-[12px] font-medium transition-colors ${filter===v?"border-brand-500 bg-blue-50 text-brand-500":"border-gray-200 bg-white text-gray-600 hover:bg-gray-100"}`}>
              {l}
            </button>
          ))}
        </div>
        <Button icon="ti-file-plus" onClick={() => setShowCreate(true)}>Create lease</Button>
      </div>

      <div className="flex flex-col gap-3">
        {filtered.length === 0 && (
          <div className="py-12 text-center bg-white border border-gray-200 rounded-xl shadow-sm">
            <i className="ti ti-file-off text-3xl text-gray-200 mb-2" aria-hidden />
            <div className="text-[13px] text-gray-400">No leases found.</div>
          </div>
        )}
        {filtered.map(lease => {
          const client  = clients.find(c => c.id === lease.clientId);
          const unit    = UNITS.find(u => u.id === lease.unitId);
          const project = unit ? PROJECTS.find(p => p.id === unit.projectId) : null;
          const ss      = STATUS_STYLES[lease.status] || STATUS_STYLES.active;
          const days    = daysUntil(lease.endDate);

          return (
            <div key={lease.id} className="bg-white border border-gray-200 rounded-xl p-5 shadow-sm hover:border-gray-300 transition-colors">
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center gap-3">
                  {client && <Avatar name={client.name} size={40} />}
                  <div>
                    <div className="text-[15px] font-semibold text-gray-900">{client?.name || "Unknown client"}</div>
                    <div className="text-[12px] text-gray-400 mt-0.5">
                      {project?.name || "–"} — Unit {unit?.unitNo || "–"} · Floor {unit?.floor || "–"}
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-2">
                  {lease.status === "expiring" && (
                    <span className="text-[12px] text-amber-600 font-semibold bg-amber-50 border border-amber-200 px-2.5 py-1 rounded-lg">
                      {days > 0 ? `Expires in ${days} days` : "Expired"}
                    </span>
                  )}
                  <Pill color={ss.color}>{ss.label}</Pill>
                </div>
              </div>

              <div className="grid grid-cols-4 gap-3 mb-4">
                {[
                  [fmt(lease.rentAmount),      "Monthly rent",     "ti-coin-rupee"  ],
                  [fmt(lease.securityDeposit), "Security deposit", "ti-shield"      ],
                  [lease.startDate,            "Start date",       "ti-calendar"    ],
                  [lease.endDate,              "End date",         "ti-calendar-off"],
                ].map(([v,l,ic]) => (
                  <div key={l} className="bg-gray-50 rounded-lg p-3 border border-gray-100">
                    <div className="flex items-center gap-1.5 mb-1">
                      <i className={`ti ${ic} text-[12px] text-gray-400`} aria-hidden />
                      <span className="text-[10px] text-gray-400 font-medium">{l}</span>
                    </div>
                    <div className="text-[13px] font-semibold text-gray-800">{v}</div>
                  </div>
                ))}
              </div>

              <div className="flex items-center justify-between pt-3 border-t border-gray-100">
                <span className="text-[12px] text-gray-400">Notice period: {lease.noticePeriod} days</span>
                <div className="flex gap-2">
                  {lease.status !== "terminated" && (
                    <>
                      <Button variant="secondary" size="sm" icon="ti-refresh"
                        onClick={() => updateLease(lease.id, { status:"active", endDate: new Date(new Date(lease.endDate).setFullYear(new Date(lease.endDate).getFullYear()+1)).toISOString().split("T")[0] })}>
                        Renew +1yr
                      </Button>
                      <Button variant="secondary" size="sm" icon="ti-download"
                        onClick={() => downloadLease(lease, client, unit, project)}>
                        Download
                      </Button>
                      <button onClick={() => terminate(lease.id)}
                        className="flex items-center gap-1.5 px-2.5 py-1.5 bg-red-50 text-red-500 border border-red-200 rounded-lg text-[12px] font-medium hover:bg-red-100 transition-colors">
                        <i className="ti ti-x text-[12px]" aria-hidden /> Terminate
                      </button>
                    </>
                  )}
                </div>
              </div>
            </div>
          );
        })}
      </div>

      {showCreate && <CreateLeaseModal onClose={() => setShowCreate(false)} />}
    </div>
  );
}

// Export CreateLeaseModal so Projects/Units can trigger it after assign
export { CreateLeaseModal };